name: mydemo
description: Turn your frame design into production-ready frontend code for mobile
  apps and web
publishTo: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
